# Generated by Django 3.1 on 2020-12-07 19:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201205_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='estado',
            field=models.CharField(max_length=25, validators=[api.models.validate_state]),
        ),
    ]
