# Generated by Django 3.1 on 2020-12-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201205_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'No activo')], default='N', max_length=25),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('N', 'No activo')], default='N', max_length=25),
        ),
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.CharField(choices=[('H', 'Habilitada'), ('D', 'Deshabilitada'), ('E', 'Eliminada')], default='D', max_length=25),
        ),
    ]
