# Generated by Django 3.1 on 2020-12-07 20:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201207_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estado',
            field=models.CharField(max_length=25, validators=[api.models.validate_state]),
        ),
    ]
